[terminal.shell]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
option_as_alt =  "Both"  # (macos only)
decorations = "Full"
dynamic_padding = false
opacity = 0.80
blur = true

[window.padding]
x = 5
y = 5

[scrolling]
history = 100000
multiplier = 3



[font]
normal = { family = "Caskaydia Cove Nerd Font ", style = "" }
size = 12
builtin_box_drawing = true 

[colors]

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }


[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"


[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"



[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"



[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false


[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15



[mouse]
hide_when_typing = false



[keyboard]
bindings = [
  { key = "Q", mods= "Command", action= "None" },
  { key = "W", mods= "Command", action= "None" },
  # vi_mode
  # If not works, check the InputSources Mac shortcuts
  { key = "Space", mods= "Control|Shift", action= "ToggleViMode" }
]

[general]

live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[terminal]
